/// Test helper utilities for SIPELOR BEDAS
/// Provides common mocks, fixtures, and utilities for testing
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

// Mock classes will be generated by build_runner
@GenerateMocks([
  SupabaseClient,
  GoTrueClient,
  User,
  Session,
  SupabaseQueryBuilder,
  SupabaseStreamBuilder,
])
void main() {}

/// Test data fixtures
class TestFixtures {
  static const String testUserId = 'test-user-id-123';
  static const String testEmail = 'test@example.com';
  static const String testBookingId = 'test-booking-123';
  static const String testVenueId = 'test-venue-123';
  static const String testFieldId = 'test-field-123';
  
  static Map<String, dynamic> mockUser() => {
    'id': testUserId,
    'email': testEmail,
    'email_confirmed_at': DateTime.now().toIso8601String(),
    'created_at': DateTime.now().toIso8601String(),
    'user_metadata': {
      'full_name': 'Test User',
      'phone': '08123456789',
    },
  };
  
  static Map<String, dynamic> mockBooking() => {
    'id': testBookingId,
    'venue_id': testVenueId,
    'field_id': testFieldId,
    'user_id': testUserId,
    'date': DateTime.now().toIso8601String(),
    'start_time': '09:00',
    'end_time': '11:00',
    'status': 'pending',
    'payment_status': 'pending',
    'total_price': 150000,
    'created_at': DateTime.now().toIso8601String(),
  };
  
  static Map<String, dynamic> mockVenue() => {
    'id': testVenueId,
    'name': 'Test Venue',
    'location': 'Test Location',
    'description': 'Test Description',
    'image_url': 'https://example.com/image.jpg',
    'rating': 4.5,
    'created_at': DateTime.now().toIso8601String(),
  };
  
  static Map<String, dynamic> mockField() => {
    'id': testFieldId,
    'venue_id': testVenueId,
    'name': 'Test Field',
    'type': 'football',
    'price_per_hour': 75000,
    'is_available': true,
    'created_at': DateTime.now().toIso8601String(),
  };
  
  static Map<String, dynamic> mockReview() => {
    'id': 'test-review-123',
    'booking_id': testBookingId,
    'user_id': testUserId,
    'venue_id': testVenueId,
    'rating': 5,
    'comment': 'Great venue!',
    'created_at': DateTime.now().toIso8601String(),
  };
  
  static Map<String, dynamic> mockChatMessage() => {
    'id': 'test-message-123',
    'booking_id': testBookingId,
    'sender_id': testUserId,
    'sender_name': 'Test User',
    'is_admin': false,
    'type': 'text',
    'message': 'Test message',
    'read': false,
    'created_at': DateTime.now().toIso8601String(),
  };
}

/// Utility to pump a widget with MaterialApp wrapper
Future<void> pumpWidgetWithMaterial(
  WidgetTester tester,
  Widget widget, {
  ThemeData? theme,
}) async {
  await tester.pumpWidget(
    MaterialApp(
      theme: theme,
      home: Scaffold(body: widget),
    ),
  );
}

/// Utility to find text containing a substring
Finder findTextContaining(String text) {
  return find.byWidgetPredicate(
    (widget) => widget is Text && 
                widget.data != null && 
                widget.data!.contains(text),
  );
}

/// Utility to wait for async operations
Future<void> waitForAsync(WidgetTester tester, {int milliseconds = 100}) async {
  await tester.pump(Duration(milliseconds: milliseconds));
  await tester.pumpAndSettle();
}
